GEMINI_MODEL = "gemini-3.1-pro-preview"
GEMINI_MODEL_HANDWRITING = "gemini-2.5-pro"
GEMINI_MAX_OUTPUT_TOKENS = 65536
GEMINI_TEMPERATURE = 0

MAX_RETRIES = 5
RATE_LIMIT_RETRY_WAIT_SECONDS = 30

PDF_RENDER_DPI = 300

COM_MAX_RETRIES = 3
COM_RETRY_WAIT_SEC = 5

USD_TO_ILS = 3.1468

CACHE_DIR_NAME = "cache"
OUTPUT_DIR_NAME = "output"
STATUS_FILE_NAME = "status.json"
COST_LOG_FILE_NAME = "api_cost_log.csv"

GEMINI_TIER_THRESHOLD = 200_000

CHUNK_SIZE_PAGES = 40
